# Generated by Django 3.0 on 2019-12-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20191206_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Urgent'), (2, 'Major'), (3, 'Moderate'), (4, 'Low')], default=3),
        ),
    ]
