# Generated by Django 3.0 on 2019-12-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20191206_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Urgent'), (1, 'Major'), (2, 'Moderate'), (3, 'Low')], default=2),
        ),
    ]
